on:
  push:
    branches: [ master, cesm3.0-alphabranch, add_preview_namelist_CI ]
  pull_request:
    branches: [ master, cesm3.0-alphabranch ]

env:
    ESMFMKFILE: ${{ env.HOME }}/esmf.mk
jobs:
  preview_namelists:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Lots of python versions, pare down if we don't support a version
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up non-python environment (need xmllint and a fake ESMF make file)
        run: |
          git config --global user.email "testing@github.actions"
          git config --global user.name "Github Actions Testing"
          echo "ESMFMKFILE is $ESMFMKFILE"
          echo "ESMF_VERSION_STRING=8.7.0" > $ESMFMKFILE
          sudo apt-get install libxml2-utils


      - name: Checkout CESM
        run: |
          $GITHUB_WORKSPACE/bin/git-fleximod update

      - name: Create new cases, run case.setup, and then preview namelists
        run: |
          cd $GITHUB_WORKSPACE/cime/scripts
          ./create_newcase --run-unsupported --mach ubuntu-latest --compset BLT1850 --res ne30pg3_t232 --case $GITHUB_WORKSPACE/cases/BLT1850_${{ matrix.python-version }}
          cd $GITHUB_WORKSPACE/cases/BLT1850_${{ matrix.python-version }}
          ./case.setup
          ./preview_namelists
          cd $GITHUB_WORKSPACE/cime/scripts
          ./create_newcase --run-unsupported --mach ubuntu-latest --compset C_JRA --res TL319_t232 --case $GITHUB_WORKSPACE/cases/C_JRA_${{ matrix.python-version }}
          cd $GITHUB_WORKSPACE/cases/C_JRA_${{ matrix.python-version }}
          ./case.setup
          ./preview_namelists
          cd $GITHUB_WORKSPACE/cime/scripts
          ./create_newcase --run-unsupported --mach ubuntu-latest --compset G_JRA --res TL319_t232 --case $GITHUB_WORKSPACE/cases/G_JRA_${{ matrix.python-version }}
          cd $GITHUB_WORKSPACE/cases/G_JRA_${{ matrix.python-version }}
          ./case.setup
          ./preview_namelists
